### ISSUE TITLE
Translate manually with transifex or smthg like that

### ISSUE THREAD

**Issue by natrius** [OpenDEM/SolidaryCityMap#2]
Leave google, seriously. Annoying.

![image](https://user-images.githubusercontent.com/7243447/76195728-3b657300-61e9-11ea-969f-d5ccdd3f92bc.png)

Put everything in strings and create a transifex for translating, that would be great :) So people can contribute to translate it and you don't need google. 

Also, when you ask about suggestions in the forum, you might check and respond as well :p

**Comment by OpenDEM** [comment]
Manually translations are possible with the editor. If you like to contribute please send me a PM for an account. Translations are also possible for languages which are not supported by Google, e.g. Central Kurdish (Sorani) – ckb and Southern Kurdish (Pehlewani)- sdh.

**Comment by natrius** [comment]
What account do you need? And a transifex would make it easier for non-technical-persons to contribute. And you should open this issue again and close it when it will be solved or if you don't want to solve it. 

1. Leave google completely (Seriously, without localization, just put english as backup. That would be better)
2. ~~Create a transifex or something similar to make translation easier~~

Well, we know you don't want transifex because its already possible via editor, so i ruled that out. Leaves point 1.

**Comment by OpenDEM** [comment]
Do you know any alternative for automatic translations, especially for languages from the conflict areas in the Middle East?

**Comment by natrius** [comment]
You are based in germany, as i can see in your impressum. You have an relatively new site, do you have some statistics for access from the conflict areas? Or do you aim for refugees? Because in this case - a lot of them are able to speak english, because the people who were able to enter the country were at least somehow educated am most probably can speak english. And i would provide a good an easy way to translate the site and then talk with them if someone is willing to work together with you. I would just not use an automatic translation program, espacially not if it stops suddenly and there is no fallback. With the donation you are basically asking people who don't have any money to donate so it can be translated - maybe you have not thought about that, i don't know. 

Look at weblate, text united, pottle or something like that for free alternatives. Maybe weblate is the weapon of choice in this case. If some people start to use it, it will get translated quite fast usally.

**Comment by OpenDEM** [comment]
Most refugees I know do not spreak english very well, but many other languages. And some of them do translations for the SolidaryCiytMap. I know the problems of other projects like "Ariving in Berlin" (a map from refugees for refugees ) with the gathering of manually translations So to break down the lanugage barriers automatic translations are the method of choice as fallback mode. There are hundreds of places maped in the app.
I had a look at the  stats, the total limit was never reached in the past month.  The only way to achive this message would be the translation of more than 100.000 charactres /100sec per user, which is quite a lot.

**Comment by natrius** [comment]
Ah, okay, okay, wel thought. I would still opt for gradually translating it manually. I don't know how i run into that infoscreen *shrug*

All the best for your project! :)
