### ISSUE TITLE
Make overly transparent and smaller

### ISSUE THREAD

**Issue by natrius** [OpenDEM/SolidaryCityMap#3]
It just hits you in the face. Make it a little bit transparent and reduce the size. Maybe 80% width and 80% height for example, something like that. Because right now it just looks like i'm suddenly on another website, ist a bit strange :D

Thanks for your work!

**Comment by OpenDEM** [comment]
The webapplication is yet only optimized for mobiles, I will put this on the TODO list.

**Comment by natrius** [comment]
Ah, okay, that explains it. Thanks for your answer :)

**Comment by OpenDEM** [comment]
I made some  fixes to make it look a little bit nicer as you suggested.

**Comment by natrius** [comment]
Guess it looks better now :)

![image](https://user-images.githubusercontent.com/7243447/77108641-dc8ecd80-6a22-11ea-9ab2-b54ea2112d24.png)

Don't ask me how i manage all the time to get that annoying google-translate-thingy...

**Comment by OpenDEM** [comment]
Do you run the app local? Then you need an google api key for the automatic translations, because there is a referrer check enabled. See Code Line 620.
